maintainer       "Boundary"
maintainer_email "j@boundary.com"
license          "Apache 2.0"
description      "Installs/Configures various apps"
long_description "Installs/Configures various apps"
version          "0.1"

depends "runit"
depends "iptables"
depends "erlang"
depends "java"
depends "git"