maintainer       "Fastip"
maintainer_email "j@fastip.com"
license          "Apache 2.0"
description      "Installs/Configures various apps"
long_description "Installs/Configures various apps"
version          "0.1"

depends "runit"
depends "iptables"
depends "erlang"